### PR TITLE
Format with mix format

### PR DESCRIPTION
**Pull request by KronicDeth**
If y'all don't feel comfortable moving the build to Elixir 1.6.1 to allow the use of `mix format --check-formatted` in the build, I can drop those commit and do the formatting locally without the check going forward.

# Changelog
## Enhancements
* Format with Elixir 1.6's `mix format`
  * Override `line_length` to `120` in `.formatter.exs` to match `config/.credo.exs`.
* Pipeline places highlighted by `mix format` changes because `mix format` itself won't transform pipelines as `mix format` won't do potential semantic changes.
* Remove commented out debugging code

### CODE REVIEW

**Comment by jeffutter** [comment]
@KronicDeth do you have any idea off-hand if it is possible to do matrix-style builds with CircleCI 2.0? It would be nice if we could make sure the build still works on 1.5 but have the 1.6 build enforce the formatting.

**Comment by KronicDeth** [comment]
@jeffutter I'm not using CircleCI for anything besides the C-S-D project, so I haven't been keeping up if they added build matrix since November.   As of November, no, there was no build matrix like Travis-CI has, we could have builds that use 1.5 and that use 1.6, but it would be a completely manually duplication in the `.circleci/config.yml`.

**Comment by KronicDeth** [comment]
Looks like the cache layering and invalidation logic is wrong in `.circleci/config.yml` and old deps are getting used although the `mix.lock` changed.  The docs for Elixir and caching have improved in CircleCI, so I'll try rewriting the cache layering to fix this.

**Comment by KronicDeth** [comment]
@jeffutter I duplicated the jobs for 1.5 builds.  The 1.5 `build_1_5` and 1.6 `build` starts immediately in parallel, so it works and seems to be [the accepted way to do it still](https://discuss.circleci.com/t/build-matrix-configuration/14448).

**Comment by jeffutter** [comment]
Yeah, I think that LGTM.

**Pull request merged**
